<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-7BTIVPCA" failures="5" tests="17" name="Test" time="0.089" errors="0" timestamp="2021-05-21T19:09:53 IST">
  <testcase classname="TestNGclass.Class1" name="myFirstTestNGMethod" time="0.008">
    <skipped/>
  </testcase> <!-- myFirstTestNGMethod -->
  <testcase classname="TestNGclass.Class1" name="myFirstTestNGMethod" time="0.001">
    <skipped/>
  </testcase> <!-- myFirstTestNGMethod -->
  <testcase classname="TestNGclass.Class1" name="myFirstTestNGMethod" time="0.001">
    <skipped/>
  </testcase> <!-- myFirstTestNGMethod -->
  <testcase classname="TestNGclass.Class1" name="myFirstTestNGMethod" time="0.002">
    <skipped/>
  </testcase> <!-- myFirstTestNGMethod -->
  <testcase classname="TestNGclass.Class1" name="myFirstTestNGMethod" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [5] but found [3]">
      <![CDATA[java.lang.AssertionError: expected [5] but found [3]
at TestNGclass.Class1.myFirstTestNGMethod(Class1.java:17)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- myFirstTestNGMethod -->
  <testcase classname="TestNGclass.Class1" name="myFirstTestNGMethod" time="0.001"/>
  <testcase classname="TestNGclass.Class1" name="myFirstTestNGMethod" time="0.001"/>
  <testcase classname="TestNGclass.Class1" name="myFirstTestNGMethod" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [5] but found [3]">
      <![CDATA[java.lang.AssertionError: expected [5] but found [3]
at TestNGclass.Class1.myFirstTestNGMethod(Class1.java:17)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- myFirstTestNGMethod -->
  <testcase classname="TestNGclass.Class1" name="myFirstTestNGMethod" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [5] but found [3]">
      <![CDATA[java.lang.AssertionError: expected [5] but found [3]
at TestNGclass.Class1.myFirstTestNGMethod(Class1.java:17)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- myFirstTestNGMethod -->
  <testcase classname="TestNGclass.Class1" name="myFirstTestNGMethod" time="0.001"/>
  <testcase classname="TestNGclass.Class1" name="myFirstTestNGMethod" time="0.0"/>
  <testcase classname="TestNGclass.Class1" name="myFirstTestNGMethod" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [5] but found [3]">
      <![CDATA[java.lang.AssertionError: expected [5] but found [3]
at TestNGclass.Class1.myFirstTestNGMethod(Class1.java:17)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- myFirstTestNGMethod -->
  <testcase classname="TestNGclass.Class1" name="myFirstTestNGMethod" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [5] but found [3]">
      <![CDATA[java.lang.AssertionError: expected [5] but found [3]
at TestNGclass.Class1.myFirstTestNGMethod(Class1.java:17)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- myFirstTestNGMethod -->
  <testcase classname="TestNGclass.Class1" name="myFirstTestNGMethod" time="0.001"/>
  <testcase classname="TestNGclass.Class1" name="myFirstTestNGMethod" time="0.001"/>
  <testcase classname="TestNGclass.Class2" name="mySecondTestNGMethod" time="0.001"/>
  <testcase classname="TestNGclass.Class2" name="mySecondTestNGMethod" time="0.0"/>
</testsuite> <!-- Test -->
